# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:GLMuXW4c8tj1Uy6Wx14dpNhlTN/81RxPcX0XYZF5p3AFqHSbfJLOag==,iv:BjmEsUmIT7xTs71IPGJ5UvAyliJoP4/HlCZhHF6HmSo=,tag:S7LmkXQtCU4PnEMjtxgjNQ==,type:str]
sops:
  age:
    - recipient: age1kw75tkwatakzwskusr290qadh7qy2c6rz0kd54wsl99ar4tgjvrqkavjcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMXZ1TnVNeTdIdUlITER4
        L2Zzay9sQ1o2Nkk2ZEZnTmI1cTRTaUVhMXlJCmMzZEFSMHVTQ3ZHenNWZlRNNTln
        cmdxZ1lwNEFJWStKZDhkNnhTOGhQc0UKLS0tIHlTRUpVZnpVZ0N3MzFhdFpLRCts
        NzA2akVwSGk4V0p0V3MrU0RaR1JPNjQK1MiH1y1DQ5myyBk7i37ZCO22KGDNTMnA
        EHC8ciDc6y/HE5VueCS85PCmEva3F7wFBDtcpQp8KoEy/5qinTwNdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-05T01:41:09Z"
  mac: ENC[AES256_GCM,data:AHwX3cE9i6GaWjuRHBmEIsjEM2dZSLYxh2/mmudyCgD8+CQhv5MyDCZcquFeQkQR4pny/rvjOFg3OKOwdVqzhhkecWZpLKoqSZKD+GGherEbNrfe8Fk74wXctveFhusVq/3+Ry3ZYrf7+pGsdEeC8wC1npZCqmiasLlBlfjuvMc=,iv:Xsg4wUh0G/0sPkjL5+C1FFO574R1wofW7NKWoQyQinU=,tag:mZ+3XA7HN3prWGjkJC27MQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
